name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Hindari shallow clone agar analisis lebih relevan

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Sesuaikan dengan versi Flutter project-mu

      - name: Install Dependencies
        run: flutter pub get

      - name: Analyze (Optional)
        run: flutter analyze

      - name: Run Tests (Optional but recommended for coverage)
        run: flutter test --coverage

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}  # Tambahkan ini jika menggunakan SonarQube Self-hosted
